#!/usr/bin/env python3
"""Create and manage per-session project pads.

Each session owns one directory under the shared Prime-Agent pad root. Pads are
independent files; the catalog is generated by listing metadata, so concurrent
sessions never need to write one shared mutable index.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from tempfile import NamedTemporaryFile


SCRIPT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ROOT = SCRIPT_ROOT.parent / "prime-agent" / "pads"
REQUIRED_SECTIONS = (
    "Intent",
    "5W1H",
    "Constraints",
    "Goal",
    "Todo",
    "State",
    "Checkpoint",
    "Definition of Done",
    "Open",
    "Decisions",
    "Notes",
    "Turn log",
)
WRITE_REASONS = (
    "task-finished",
    "pivot",
    "verified-result",
    "checkpoint",
    "blocked",
    "handoff",
)


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def root_from(value: str | None) -> Path:
    raw = value or os.environ.get("PRIME_PROJECT_PAD_ROOT")
    return Path(raw).expanduser().resolve() if raw else DEFAULT_ROOT


def fail(message: str) -> "NoReturn":
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


def ensure_root(root: Path) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    return root


def ensure_pad_path(root: Path, value: str) -> Path:
    path = Path(value).expanduser().resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError:
        fail(f"pad must be inside {root}")
    if path.name != "pad.md":
        fail("pad path must end in pad.md")
    return path


def metadata_path(pad_path: Path) -> Path:
    return pad_path.with_name("metadata.json")


def load_metadata(pad_path: Path) -> dict:
    path = metadata_path(pad_path)
    if not path.is_file():
        fail(f"metadata missing beside {pad_path}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"invalid metadata JSON: {exc}")
    if not isinstance(value, dict):
        fail("metadata must be an object")
    return value


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=path.parent, delete=False) as handle:
        handle.write(content)
        temp_path = Path(handle.name)
    temp_path.replace(path)


def play_pad_template(session_id: str, actor: str, label: str, created_at: str) -> str:
    return f"""# Session pad

## Session

- **Session ID:** `{session_id}`
- **Actor:** `{actor}`
- **Label:** {label or "unlabeled"}
- **Created:** {created_at}
- **Status:** active
- **Pad ownership:** this session only

## Intent

Play Minecraft as PrimeBot. Do not write files.

## 5W1H

- **What:** play Minecraft
- **Why:** in-game goals from the player
- **Who:** decider the player; owner {actor}; face PrimeBot
- **When:** this session
- **Where:** the live Survival world
- **How:** `start_presence` and `presence_action`

## Constraints

- **Must not break:**
  - Do not write another session's pad.
  - Do not update this pad for ordinary conversation.
  - Do not read or write files outside this pad.

## Goal

Wait for in-game chat, then play that goal. Stay in the world after.

## Todo

- [ ] `start_presence()` and idle until the player gives an in-game goal.

## State

No in-game goal yet.

## Checkpoint

- {created_at}: expected: session pad exists and is readable; actual: initialized.

## Definition of Done

- [ ] The in-game goal is attempted with `presence_action`.
- [ ] PrimeBot stays in the world.
- [ ] No project files were edited.

## Open

- What remains unknown or needs another session?

## Decisions

- This session plays Minecraft. It does not own project code.

## Notes

Keep compact, evidence-backed notes here. Do not write skills or project files.

## Turn log

- {created_at}: pad created.
"""


def pad_template(session_id: str, actor: str, label: str, created_at: str, profile: str = "") -> str:
    if profile == "play":
        return play_pad_template(session_id, actor, label, created_at)
    return f"""# Session pad

## Session

- **Session ID:** `{session_id}`
- **Actor:** `{actor}`
- **Label:** {label or "unlabeled"}
- **Created:** {created_at}
- **Status:** active
- **Pad ownership:** this session only

## Intent

State the one-sentence intent before substantive work.

## 5W1H

- **What:** unknown
- **Why:** unknown
- **Who:** decider unknown; owner {actor}; face unknown
- **When:** unknown
- **Where:** unknown
- **How:** unknown

## Constraints

- **Must not break:**
  - Do not write another session's pad.
  - Do not update this pad for ordinary conversation.
  - Keep project artifacts in the configured D: project roots.

## Goal

Define the smallest outcome this session must finish.

## Todo

- [ ] Initialize the session framing and inspect the shared catalog.

## State

No substantive work has been performed yet.

## Checkpoint

- {created_at}: expected: session pad exists and is readable; actual: initialized.

## Definition of Done

- [ ] Intent and 5W1H are filled.
- [ ] Constraints are checked before substantive work.
- [ ] The session's result and unresolved work are recorded.

## Open

- What remains unknown or needs another session?

## Decisions

- Each session owns one pad; other pads are read-only references.

## Notes

Keep compact, evidence-backed notes here. Put durable artifacts in the project.

## Turn log

- {created_at}: pad created.
"""


def command_new(args: argparse.Namespace) -> int:
    root = ensure_root(root_from(args.root))
    created_at = utc_now()
    session_id = args.session_id or f"{args.actor}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:12]}"
    session_dir = root / session_id
    if session_dir.exists():
        fail(f"session pad already exists: {session_id}")
    session_dir.mkdir(parents=True)
    pad_path = session_dir / "pad.md"
    metadata = {
        "schema": "project-session-pad",
        "schema_version": 1,
        "session_id": session_id,
        "actor": args.actor,
        "label": args.label or "",
        "owner": session_id,
        "status": "active",
        "created_at": created_at,
        "updated_at": created_at,
        "pad_path": str(pad_path),
        "root": str(root),
    }
    atomic_write(metadata_path(pad_path), json.dumps(metadata, indent=2) + "\n")
    atomic_write(
        pad_path,
        pad_template(session_id, args.actor, args.label, created_at, profile=getattr(args, "profile", "") or ""),
    )
    print(json.dumps(metadata, indent=2))
    return 0


def iter_metadata(root: Path) -> list[dict]:
    if not root.exists():
        return []
    values: list[dict] = []
    for path in root.glob("*/metadata.json"):
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(value, dict) and isinstance(value.get("created_at"), str):
            values.append(value)
    return sorted(values, key=lambda value: value["created_at"], reverse=True)


def command_list(args: argparse.Namespace) -> int:
    root = root_from(args.root)
    values = iter_metadata(root)
    if args.actor:
        values = [value for value in values if value.get("actor") == args.actor]
    if args.json:
        print(json.dumps(values, indent=2))
        return 0
    if not values:
        print(f"No pads found under {root}")
        return 0
    for value in values:
        print(f"{value.get('session_id')}\t{value.get('actor')}\t{value.get('status')}\t{value.get('pad_path')}")
    return 0


def command_latest(args: argparse.Namespace) -> int:
    root = root_from(args.root)
    values = iter_metadata(root)
    if args.actor:
        values = [value for value in values if value.get("actor") == args.actor]
    if not values:
        fail(f"no matching pads under {root}")
    value = values[0]
    if args.json:
        print(json.dumps(value, indent=2))
    else:
        print(value["pad_path"])
    return 0


def resolve_pad(args: argparse.Namespace) -> Path:
    root = root_from(args.root)
    if args.path:
        return ensure_pad_path(root, args.path)
    if args.session_id:
        return ensure_pad_path(root, str(root / args.session_id / "pad.md"))
    fail("provide --path or --session-id")


def command_read(args: argparse.Namespace) -> int:
    pad_path = resolve_pad(args)
    if not pad_path.is_file():
        fail(f"pad missing: {pad_path}")
    sys.stdout.write(pad_path.read_text(encoding="utf-8"))
    return 0


def validate_content(content: str) -> list[str]:
    headings = set(re.findall(r"^## (.+?)\s*$", content, flags=re.MULTILINE))
    return [section for section in REQUIRED_SECTIONS if section not in headings]


def section_body(content: str, section: str) -> str:
    match = re.search(
        rf"^## {re.escape(section)}\s*$([\s\S]*?)(?=^## |\Z)",
        content,
        flags=re.MULTILINE,
    )
    return match.group(1).strip() if match else ""


def check_owner(pad_path: Path, requested_owner: str | None) -> None:
    metadata = load_metadata(pad_path)
    effective_owner = requested_owner or os.environ.get("PRIME_PROJECT_PAD_OWNER")
    if not effective_owner:
        fail("owner is required for writes; pass --owner or set PRIME_PROJECT_PAD_OWNER")
    if metadata.get("owner") != effective_owner:
        fail("owner mismatch; a session may only write its own pad")


def command_validate(args: argparse.Namespace) -> int:
    pad_path = resolve_pad(args)
    if not pad_path.is_file():
        fail(f"pad missing: {pad_path}")
    metadata = load_metadata(pad_path)
    missing = validate_content(pad_path.read_text(encoding="utf-8"))
    if missing:
        fail("missing sections: " + ", ".join(missing))
    if metadata.get("session_id") != pad_path.parent.name:
        fail("metadata session_id does not match its directory")
    print(json.dumps({"status": "valid", "pad_path": str(pad_path), "session_id": metadata["session_id"]}, indent=2))
    return 0


def command_write(args: argparse.Namespace) -> int:
    pad_path = resolve_pad(args)
    if not pad_path.is_file():
        fail(f"pad missing: {pad_path}")
    check_owner(pad_path, args.owner)
    content = sys.stdin.read()
    if not content.strip():
        fail("refusing to replace a pad with empty input")
    missing = validate_content(content)
    if missing:
        fail("missing sections: " + ", ".join(missing))
    previous_content = pad_path.read_text(encoding="utf-8")
    previous_checkpoint = section_body(previous_content, "Checkpoint")
    next_checkpoint = section_body(content, "Checkpoint")
    if previous_checkpoint and previous_checkpoint not in next_checkpoint:
        fail("checkpoint history is append-only; preserve prior checkpoint entries")
    metadata = load_metadata(pad_path)
    metadata["updated_at"] = utc_now()
    metadata["last_write_reason"] = args.reason
    atomic_write(pad_path, content if content.endswith("\n") else content + "\n")
    atomic_write(metadata_path(pad_path), json.dumps(metadata, indent=2) + "\n")
    print(json.dumps({"status": "written", "reason": args.reason, "pad_path": str(pad_path)}, indent=2))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="manage isolated per-session project pads")
    subparsers = parser.add_subparsers(dest="command", required=True)

    new = subparsers.add_parser("new", help="create one owned session pad")
    new.add_argument("--root")
    new.add_argument("--actor", choices=("prime", "codex", "coordinator", "delegated"), required=True)
    new.add_argument("--session-id")
    new.add_argument("--label", default="")
    new.add_argument("--profile", default="", choices=("", "play", "optimize", "default"))
    new.set_defaults(function=command_new)

    list_command = subparsers.add_parser("list", help="list pads without writing a shared index")
    list_command.add_argument("--root")
    list_command.add_argument("--actor")
    list_command.add_argument("--json", action="store_true")
    list_command.set_defaults(function=command_list)

    latest = subparsers.add_parser("latest", help="resolve the newest pad")
    latest.add_argument("--root")
    latest.add_argument("--actor")
    latest.add_argument("--json", action="store_true")
    latest.set_defaults(function=command_latest)

    for name, function in (("read", command_read), ("validate", command_validate)):
        command = subparsers.add_parser(name, help=f"{name} one pad")
        command.add_argument("--root")
        command.add_argument("--path")
        command.add_argument("--session-id")
        command.set_defaults(function=function)

    write = subparsers.add_parser("write", help="replace a pad after an explicit non-trivial update")
    write.add_argument("--root")
    write.add_argument("--path")
    write.add_argument("--session-id")
    write.add_argument("--owner")
    write.add_argument("--reason", choices=WRITE_REASONS, required=True)
    write.set_defaults(function=command_write)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.function(args))


if __name__ == "__main__":
    main()
