import fs from 'node:fs/promises';
import path from 'node:path';
export const DEFAULT = ['target_dx','target_dy','target_dz','target_vx','target_vy','target_vz','distance','bearing','elevation','angular_error_yaw','angular_error_pitch','line_of_sight','in_reach','self_health','target_health','on_ground','cooldown','is_sprinting','is_sneaking','target_zombie','target_skeleton','target_enderman','target_blaze','target_phantom','has_sword','has_axe','has_shield','dimension_overworld','dimension_nether','dimension_end','support_center','support_forward','support_back','support_left','support_right','drop_forward','drop_back','drop_left','drop_right','clearance_forward','clearance_back','clearance_left','clearance_right','hazard_near','incoming_swing','recent_damage'];
export function policyFeatures(observation, targetType = '') {
  const t = observation?.target ?? {}, s = observation?.self ?? {}, terrain=observation?.terrain??{}, rel = t.relative_position ?? {x:0,y:0,z:0}, vel = t.velocity ?? {x:0,y:0,z:0}, dim=String(observation?.dimension??terrain.dimension??'').toLowerCase();
  const equipment=String(s.held_item??'')+' '+String(s.offhand_item??'');
  const v = { target_dx:rel.x ?? 0, target_dy:rel.y ?? 0, target_dz:rel.z ?? 0, target_vx:vel.x ?? 0, target_vy:vel.y ?? 0, target_vz:vel.z ?? 0, distance:t.distance ?? 0, bearing:t.bearing ?? 0, elevation:t.elevation ?? 0, angular_error_yaw:t.angular_error?.yaw ?? 0, angular_error_pitch:t.angular_error?.pitch ?? 0, line_of_sight:t.line_of_sight ? 1 : 0, in_reach:t.in_reach ? 1 : 0, self_health:s.health ?? 20, target_health:t.health ?? 20, on_ground:s.on_ground ? 1:0, cooldown:s.cooldown ?? 0, is_sprinting:s.sprinting ? 1:0, is_sneaking:s.sneaking ? 1:0, target_zombie:targetType==='zombie' ? 1:0, target_skeleton:targetType==='skeleton' ? 1:0, target_enderman:targetType==='enderman' ? 1:0, target_blaze:targetType==='blaze' ? 1:0, target_phantom:targetType==='phantom' ? 1:0, has_sword:/sword/i.test(equipment) ? 1:0, has_axe:/axe/i.test(equipment) ? 1:0, has_shield:/shield/i.test(equipment) ? 1:0, dimension_overworld:dim.endsWith('overworld')?1:0, dimension_nether:dim.endsWith('nether')?1:0, dimension_end:dim.endsWith('end')?1:0, incoming_swing:s.incoming_attack?.swing_detected?1:0, recent_damage:s.incoming_attack?.damage??0, ...terrain };
  return DEFAULT.map((k) => Number.isFinite(v[k]) ? v[k] : 0);
}
export class TacticalPolicy {
  constructor({ modelPath, metadataPath, targetType = '' } = {}) { this.modelPath=modelPath; this.metadataPath=metadataPath; this.targetType=targetType; this.session=null; this.mean=[]; this.std=[]; }
  async load() { if (!this.modelPath) return false; try { const ort = await import('onnxruntime-node'); this.session = await ort.InferenceSession.create(this.modelPath); if (this.metadataPath) { const m=JSON.parse(await fs.readFile(this.metadataPath,'utf8')); const n=m.normalization??m; this.mean=n.mean ?? []; this.std=n.std ?? []; } return true; } catch { this.session=null; return false; } }
  async infer(history) { const n=history.flatMap((o)=>policyFeatures(o,this.targetType)); if (!this.session) return {}; const ort=await import('onnxruntime-node'); const norm=n.map((x,i)=> (x-(this.mean[i]??0))/(this.std[i]||1)); const input=new ort.Tensor('float32', Float32Array.from(norm), [1,norm.length]); const out=await this.session.run({observations:input}); const vals=Array.from(out.logits.data); const keys=['forward','back','left','right','jump','sprint','sneak','attack','use','disengage']; return Object.fromEntries(keys.map((k,i)=>[k,(1/(1+Math.exp(-vals[i]))) >= .5])); }
}
